//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStoreInfo
    {
        public int StoreId { get; set; }
        public string StoreName { get; set; }
        public string StoreAddress { get; set; }
        public string Pincode { get; set; }
        public string SearchTags { get; set; }
        public Nullable<int> AdminApprove { get; set; }
        public string StoreAuthId { get; set; }
    }
}
