//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductInfo
    {
        public int ProductId { get; set; }
        public string Category { get; set; }
        public string BrandName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string StoreAuthId { get; set; }
    }
}
